cache:
  npm: true

notifications:
  email: false

os: linux
dist: focal

arch: amd64

language: node_js

node_js:
  - 15

stages:
  - test

jobs:
  include:
    - stage: test
      before_install:
        - node -v
        - npm -v
      install:
        - npm i
      script:
        - npm run test
